name = "EPCA"
uuid = "5eea3c19-248f-4333-a7fb-b3d728c4ea9c"
authors = ["Logan Mondal Bhamidipaty <76822456+FlyingWorkshop@users.noreply.github.com>"]
version = "0.1.0"

[deps]
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
