name = "ExponentialFamilyPCA"
uuid = "11e87cda-3a35-409a-8e6b-280a62a99146"
authors = ["Logan Mondal Bhamidipaty <76822456+FlyingWorkshop@users.noreply.github.com>"]
version = "0.1.0"

[deps]
CompressedBeliefPOMDPs = "5eea3c19-248f-4333-a7fb-b3d728c4ea9c"
